// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-JX7dsXgvQnG2LBE8WjZl87FLkhyvOI',
    appId: '1:363359268417:web:e7e356e01bb81798b960c0',
    messagingSenderId: '363359268417',
    projectId: 'gradproj-cfcb3',
    authDomain: 'gradproj-cfcb3.firebaseapp.com',
    storageBucket: 'gradproj-cfcb3.firebasestorage.app',
    measurementId: 'G-3WR2V88MES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6qIV9Y1TuM-0SrOc-F7dZitPAYn4xns',
    appId: '1:363359268417:android:7ded10be09302e07b960c0',
    messagingSenderId: '363359268417',
    projectId: 'gradproj-cfcb3',
    storageBucket: 'gradproj-cfcb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFdrhMJk9Do2908IJYdL4N3NNrTH0df4',
    appId: '1:363359268417:ios:3950b037ed4eb3f1b960c0',
    messagingSenderId: '363359268417',
    projectId: 'gradproj-cfcb3',
    storageBucket: 'gradproj-cfcb3.firebasestorage.app',
    iosBundleId: 'com.example.grproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJFdrhMJk9Do2908IJYdL4N3NNrTH0df4',
    appId: '1:363359268417:ios:3950b037ed4eb3f1b960c0',
    messagingSenderId: '363359268417',
    projectId: 'gradproj-cfcb3',
    storageBucket: 'gradproj-cfcb3.firebasestorage.app',
    iosBundleId: 'com.example.grproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-JX7dsXgvQnG2LBE8WjZl87FLkhyvOI',
    appId: '1:363359268417:web:73015a24f06706e4b960c0',
    messagingSenderId: '363359268417',
    projectId: 'gradproj-cfcb3',
    authDomain: 'gradproj-cfcb3.firebaseapp.com',
    storageBucket: 'gradproj-cfcb3.firebasestorage.app',
    measurementId: 'G-Z3LWL2QQRZ',
  );
}
